name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Packages
      run: |
        sudo apt update -qq
        sudo apt install -y git build-essential g++ make
        sudo apt-get install -y --no-install-recommends libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libgl1-mesa-dev
    
    - name: Fetch git submodules
      run: git submodule update --init --recursive
    
    - name: premake5
      run: ./premake5 gmake2

    - name: make Debug x64
      run: make config=debug_x64
      
    - name: make Dist x64
      run: make config=dist_x64

  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    
    steps:
      # ...
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: false
          files: |
            Game/assets/*
            bin/Dist-linux-x86_64/Game/Game
